name: Node.js CI (Backend)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**' # Specify the backend directory path here

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x,18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      working-directory: backend # Set the working directory to backend
      run: npm ci
